Bakery/Models/Treat.cs
using System.Collections.Generic;

namespace Bakery.Models
{
    public class Treat
    {
        public int TreatId { get; set; }
        public string Name { get; set; }
        public List<TreatFlavor> TreatFlavors { get; set; }
    }
}

Bakery/Controllers/TreatsController.cs
using Microsoft.AspNetCore.Mvc;
using Bakery.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;

namespace Bakery.Controllers
{
    [Authorize]
    public class TreatsController : Controller
    {
        private readonly BakeryContext _db;
        private readonly UserManager<ApplicationUser> _userManager;

        public TreatsController(BakeryContext db, UserManager<ApplicationUser> userManager)
        {
            _db = db;
            _userManager = userManager;
        }

        [AllowAnonymous]
        public ActionResult Index()
        {
            List<Treat> treats = _db.Treats.ToList();
            return View(treats);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Treat treat)
        {
            _db.Treats.Add(treat);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        [AllowAnonymous]
        public ActionResult Details(int id)
        {
            Treat treat = _db.Treats
                .Include(m => m.TreatFlavors)
                .ThenInclude(m => m.Flavor)
                .FirstOrDefault(model => model.TreatId == id);
            return View(treat);
        }

        public ActionResult Update(int id)
        {
            Treat treat = _db.Treats.FirstOrDefault(model => model.TreatId == id);
            return View(treat);
        }

        [HttpPost]
        public ActionResult Update(Treat treat)
        {
            _db.Update(treat);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            Treat treat = _db.Treats.FirstOrDefault(model => model.TreatId == id);
            return View(treat);
        }

        [HttpPost]
        public ActionResult Delete(Treat treat)
        {
            _db.Remove(treat);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult AddFlavor(int id)
        {
            Treat treat = _db.Treats
                .FirstOrDefault(model => model.TreatId == id);
            ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "Name");
            return View(treat);
        }

        [HttpPost]
        public ActionResult AddFlavor(Treat treat, int flavorId)
        {
#nullable enable
            TreatFlavor? treatFlavor = _db.TreatFlavors
                .FirstOrDefault(model => model.FlavorId == flavorId && model.TreatId == treat.TreatId);
#nullable disable
            if (treatFlavor == null && flavorId != 0)
            {
                _db.TreatFlavors.Add(new TreatFlavor() { FlavorId = flavorId, TreatId = treat.TreatId });
                _db.SaveChanges();
            }
            return RedirectToAction("Details", new { id = treat.TreatId });
        }
    }
}

Bakery/Views/Treats/AddFlavor.cshtml
@model Bakery.Models.Treat
@using Bakery.Models

@{
    Layout = "_Layout";
}

<h2>Treats</h2>
<hr>
<h3>Add a flavor to: @Html.DisplayFor(model => model.Name)</h3>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.TreatId)

    @Html.Label("Select flavor")
    @Html.DropDownList("FlavorId")

    <input type="submit" value="Add Flavor" />
}

Bakery/Views/Treats/Create.cshtml
@{
    Layout = "_Layout";
}

@model Bakery.Models.Treat

<h2>Treats</h2>
<hr>
<h3>New Treat</h3>

@using (Html.BeginForm("Create", "Treats"))
{
    @Html.LabelFor(model => model.Name)
    @Html.TextBoxFor(model => model.Name, new {required="true"})
    <input type="submit" value="Add Treat" />
}

Bakery/Views/Treats/Delete.cshtml
@{
    Layout = "_Layout";
}
@model Bakery.Models.Treat

<h2>Treats</h2>
<hr>
<h3>Delete Treat @Model.Name</h3>

@using (Html.BeginForm("Delete", "Treats"))
{
    @Html.HiddenFor(model => model.TreatId)
    <input type="submit" value="Delete Treat" />
}

Bakery/Views/Treats/Details.cshtml
@{
    Layout = "_Layout";
}

@model Bakery.Models.Treat
@using Bakery.Models

<h2>Treats</h2>
<hr>
<h3>View Treat</h3>

<p>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</p>

<h4>Flavors</h4>
@if (@Model.TreatFlavors.Count == 0)
{
    <p>This treat does not have any flavors.</p>
}
@foreach (TreatFlavor treatFlavor in Model.TreatFlavors)
{
    <p>@treatFlavor.Flavor.Name</p>
}

@Html.ActionLink("Add Flavor", "AddFlavor", new {id = Model.TreatId}, new {@class="btn small"})
@Html.ActionLink("Edit Treat", "Update", new {id = Model.TreatId}, new {@class="btn small"})
@Html.ActionLink("Delete Treat", "Delete", new {id = Model.TreatId}, new {@class="btn small"})

Bakery/Views/Treats/Index.cshtml
@{
    Layout = "_Layout";
}

@using Bakery.Models

<h2>Treats</h2>
<hr>
<h3>Treat Navigator</h3>

@if (Model.Count == 0)
{
    <p>No treats</p>
}
@foreach (Treat treat in Model)
{
    @Html.ActionLink(treat.Name, "Details", new {id = treat.TreatId}, new {@class="btn small item"})
    <br>
}

@Html.ActionLink("New Treat", "Create", "Treats", new {}, new {@class="btn small"})

Bakery/Views/Treats/Update.cshtml
@{
    Layout = "_Layout";
}

@model Bakery.Models.Treat

<h2>Treats</h2>
<hr>
<h3>Edit Treat</h3>

@using (Html.BeginForm("Update", "Treats"))
{
    @Html.HiddenFor(model => model.TreatId)
    @Html.LabelFor(model => model.Name)
    @Html.TextBoxFor(model => model.Name, new {required="true"})
    <input type="submit" value="Update Treat" />
}