Bakery/Models/Flavor.cs
using System.Collections.Generic;
using Bakery.Migrations;

namespace Bakery.Models
{
    public class Flavor
    {
        public int FlavorId { get; set; }
        public string Name { get; set; }
        public List<TreatFlavor> TreatFlavors { get; set; }
    }
}

Bakery/Controllers/FlavorsController.cs
using Microsoft.AspNetCore.Mvc;
using Bakery.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;

namespace Bakery.Controllers
{
    [Authorize]
    public class FlavorsController : Controller
    {
        private readonly BakeryContext _db;
        private readonly UserManager<ApplicationUser> _userManager;

        public FlavorsController(BakeryContext db, UserManager<ApplicationUser> userManager)
        {
            _db = db;
            _userManager = userManager;
        }

        [AllowAnonymous]
        public ActionResult Index()
        {
            List<Flavor> flavors = _db.Flavors.ToList();
            return View(flavors);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Flavor flavor)
        {
            _db.Flavors.Add(flavor);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        [AllowAnonymous]
        public ActionResult Details(int id)
        {
            Flavor flavor = _db.Flavors
                .Include(m => m.TreatFlavors)
                .ThenInclude(m => m.Treat)
                .FirstOrDefault(model => model.FlavorId == id);
            return View(flavor);
        }

        public ActionResult Update(int id)
        {
            Flavor flavor = _db.Flavors.FirstOrDefault(model => model.FlavorId == id);
            return View(flavor);
        }

        [HttpPost]
        public ActionResult Update(Flavor flavor)
        {
            _db.Update(flavor);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            Flavor flavor = _db.Flavors.FirstOrDefault(model => model.FlavorId == id);
            return View(flavor);
        }

        [HttpPost]
        public ActionResult Delete(Flavor flavor)
        {
            _db.Remove(flavor);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult AddTreat(int id)
        {
            Flavor flavor = _db.Flavors
                .FirstOrDefault(model => model.FlavorId == id);
            ViewBag.TreatId = new SelectList(_db.Treats, "TreatId", "Name");
            return View(flavor);
        }

        [HttpPost]
        public ActionResult AddTreat(Flavor flavor, int treatId)
        {
#nullable enable
            TreatFlavor? treatFlavor = _db.TreatFlavors
                .FirstOrDefault(model => (model.TreatId == treatId && model.FlavorId == flavor.FlavorId));
#nullable disable
            if (treatFlavor == null && treatId != 0)
            {
                _db.TreatFlavors.Add(new TreatFlavor() { TreatId = treatId, FlavorId = flavor.FlavorId });
                _db.SaveChanges();
            }
            return RedirectToAction("Details", new { id = flavor.FlavorId });
        }
    }
}

Bakery/Views/Flavors/AddTreat.cshtml
@model Bakery.Models.Flavor
@using Bakery.Models

@{
    Layout = "_Layout";
}

<h2>Flavors</h2>
<hr>
<h3>Add a treat to: @Html.DisplayFor(model => model.Name)</h3>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.FlavorId)

    @Html.Label("Select treat")
    @Html.DropDownList("TreatId")

    <input type="submit" value="Add Treat" />
}

Bakery/Views/Flavors/Create.cshtml
@{
    Layout = "_Layout";
}

<h2>Flavors</h2>
<hr>
<h3>New Flavor</h3>

@model Bakery.Models.Flavor

@using (Html.BeginForm("Create", "Flavors"))
{
    @Html.LabelFor(model => model.Name)
    @Html.TextBoxFor(model => model.Name, new {required="true"})
    <input type="submit" value="Add Flavor" />
}

Bakery/Views/Flavors/Delete.cshtml
@{
    Layout = "_Layout";
}
@model Bakery.Models.Flavor

<h2>Flavors</h2>
<hr>
<h3>Delete Flavor @Model.Name</h3>

@using (Html.BeginForm("Delete", "Flavors"))
{
    @Html.HiddenFor(model => model.FlavorId)
    <input type="submit" value="Delete Flavor" />
}

Bakery/Views/Flavors/Details.cshtml
@{
    Layout = "_Layout";
}

@model Bakery.Models.Flavor
@using Bakery.Models

<h2>Flavors</h2>
<hr>
<h3>View Flavor</h3>

<p>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</p>

<h4>Treats</h4>
@if (@Model.TreatFlavors.Count == 0)
{
    <p>This flavor does not apply to any treats.</p>
}
@foreach (TreatFlavor treatFlavor in Model.TreatFlavors)
{
    <p>@treatFlavor.Treat.Name</p>
}

@Html.ActionLink("Add Treat", "AddTreat", new {id = Model.FlavorId}, new {@class="btn small"})
@Html.ActionLink("Edit Flavor", "Update", new {id = Model.FlavorId}, new {@class="btn small"})
@Html.ActionLink("Delete Flavor", "Delete", new {id = Model.FlavorId}, new {@class="btn small"})

Bakery/Views/Flavors/Index.cshtml
@{
    Layout = "_Layout";
}

@using Bakery.Models

<h2>Flavors</h2>
<hr>
<h3>Flavor Navigator</h3>

@if (Model.Count == 0)
{
    <p>No flavors</p>
}
@foreach (Flavor flavor in Model)
{
    @Html.ActionLink(flavor.Name, "Details", new {id = flavor.FlavorId}, new {@class="btn small item"})
    <br>
}

@Html.ActionLink("New Flavor", "Create", "Flavors", new {}, new {@class="btn small"})

Bakery/Views/Flavors/Update.cshtml
@{
    Layout = "_Layout";
}

@model Bakery.Models.Flavor

<h2>Flavors</h2>
<hr>
<h3>Edit Flavor</h3>

@using (Html.BeginForm("Update", "Flavors"))
{
    @Html.HiddenFor(model => model.FlavorId)
    @Html.LabelFor(model => model.Name)
    @Html.TextBoxFor(model => model.Name, new {required="true"})
    <input type="submit" value="Update Flavor" />
}